=== jmpesculturas/IFCD0210/MF0491-3 CLIENTE/UF1841/E2/prueba1xmljuanmanuelparrado.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2019 rel. 3 sp1 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="artista">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="bernini"/>
				<xs:enumeration value="camile claudel"/>
				<xs:enumeration value="javier murcia"/>
				<xs:enumeration value="juan manuel"/>
				<xs:enumeration value="miguel angel"/>
				<xs:enumeration value="roden"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="escultor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="artista"/>
				<xs:element ref="pais"/>
				<xs:element ref="obra"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="escultores">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="escultor" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="obra">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="1969"/>
				<xs:enumeration value="david"/>
				<xs:enumeration value="jocker"/>
				<xs:enumeration value="los amantes"/>
				<xs:enumeration value="los pescadores"/>
				<xs:enumeration value="pensador"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="pais">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="espaÃ±a"/>
				<xs:enumeration value="francia"/>
				<xs:enumeration value="italia"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== jmpesculturas/IFCD0210/MF0491-3 CLIENTE/UF1841/E2/prueba 1 xml juan manuel parrado.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo-escultores.css"?>
<escultores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/IFCD0210/MF0491-3%20CLIENTE/UF1841/E2/prueba1xmljuanmanuelparrado.xsd">
	<escultor>
		<artista>miguel angel</artista>
		<pais>italia</pais>
		<obra>david</obra>
	</escultor>
	<escultor>
		<artista>roden</artista>
		<pais>francia</pais>
		<obra>pensador</obra>
	</escultor>
	<escultor>
		<artista>bernini</artista>
		<pais>italia</pais>
		<obra>1969</obra>
	</escultor>
	<escultor>
		<artista>camile claudel</artista>
		<pais>francia</pais>
		<obra>los amantes</obra>
	</escultor>
	<escultor>
		<artista>javier murcia</artista>
		<pais>españa</pais>
		<obra>los pescadores</obra>
	</escultor>
	<escultor>
		<artista>juan manuel</artista>
		<pais>españa</pais>
		<obra>jocker</obra>
	</escultor>

</escultores>
